# Generated by Django 5.1.7 on 2025-04-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techstore', '0003_supplyorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rv_details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='reference_details',
            field=models.CharField(max_length=100),
        ),
    ]
