# Generated by Django 5.1.7 on 2025-04-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techstore', '0005_loanregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanregister',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanregister',
            name='loaned_item_returned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
