# Generated by Django 5.1.7 on 2025-04-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techstore', '0007_usersupplyorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersupplyorder',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
