# Generated by Django 5.1.7 on 2025-04-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techstore', '0008_usersupplyorder_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersupplyorder',
            name='item_returned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
